/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    fontFamily: {
      sans: ['Inter Tight', 'serif'],
      lastik: ['Lastik', 'serif'],
    },
    screens: {
      xxs: '320px',
      xs: '350px',
      sm: '568px',
      md: '768px',
      lg: '1024px',
      xl: '1200px',
    },
    extend: {
      colors: {
        primary: '#999',
        secondary: '#202123',
      },
      backgroundImage: {
        'bg-1': "url('/images/bg-1.jpg')",
        'bg-2': "url('/images/bg-2.jpg')",
        'bg-2-1': "url('/images/bg-2-1.png')",
        'bg-3': "url('/images/bg-3.jpg')",
        'bg-4': "url('/images/bg-4.jpg')",
        'bg-5': "url('/images/bg-5.jpg')",
        'bg-5-1': "url('/images/bg-5-1.png')",
        'bg-6': "url('/images/bg-6.jpg')",
        'bg-6-1': "url('/images/bg-6-1.png')",
        'bg-7': "url('/images/bg-7.jpg')",
        'bg-7-1': "url('/images/bg-7-1.png')",
        'bg-8': "url('/images/bg-8.png')",
        'bg-8-1': "url('/images/bg-8-1.png')",
        'bg-9': "url('/images/bg-9.png')",
        'bg-9-1': "url('/images/bg-9-1.png')",
        'bg-10': "url('/images/bg-10.png')",
        'bg-10-1': "url('/images/bg-10-1.png')",
        'bg-11': "url('/images/bg-11.png')",
        'bg-11-1': "url('/images/bg-11-1.png')",
        'bg-12': "url('/images/bg-12.png')",
        'bg-12-1': "url('/images/bg-12-1.png')",
        'bg-13': "url('/images/bg-13.png')",
        'bg-13-1': "url('/images/bg-13-1.png')",
        'bg-14': "url('/images/bg-14.png')",
        'bg-14-1': "url('/images/bg-14-1.png')",
        'bg-15': "url('/images/bg-15.png')",
        'bg-15-1': "url('/images/bg-15-1.png')",
        'bg-16': "url('/images/bg-16.png')",
        'bg-16-1': "url('/images/bg-16-1.png')",
        'bg-17': "url('/images/bg-17.png')",
        'bg-17-1': "url('/images/bg-17-1.png')",
        'bg-18': "url('/images/bg-18.png')",
        'bg-19': "url('/images/bg-19.png')",
        'bg-20': "url('/images/bg-20.png')",
        'bg-21': "url('/images/bg-21.png')",
        'bg-22': "url('/images/bg-22.png')",
        'next-16': "url('/images/next-16.png')",
        'next-17': "url('/images/next-17.png')",
        'next-18': "url('/images/next-18.png')",
        'next-19': "url('/images/next-19.png')",
        'next-20': "url('/images/next-20.png')",
        'next-21': "url('/images/next-21.png')",
        'next-22': "url('/images/next-22.png')",
      },
    },
  },
  plugins: [],
};
