export const casesData = [
  {
    background: 'bg-bg-1',
    title: 'Лига уличного футбола',
    link: '/case15',
    cards: ['брендинг', 'UX/UI-дизайн', 'events', 'партнерство'],
  },
  {
    background: 'bg-bg-2-1',
    title: 'запуск nrav',
    link: '/case3',
    cards: ['events'],
  },
  {
    background: 'bg-bg-3',
    title: 'Pop-up «Самолет»',
    link: '/case7',
    cards: ['events', 'архитектура'],
  },
  {
    background: 'bg-bg-4',
    title: 'Rebranding lunda',
    link: '/case10',
    cards: ['брендинг', '3d', 'партнерство'],
  },
  {
    background: 'bg-bg-5-1',
    title: 'betboom party',
    link: '/case9',
    cards: ['events'],
  },
  {
    background: 'bg-bg-6-1',
    title: 'маскот УК « Альфа-капитал »',
    link: '/case1',
    cards: ['3d', 'стратегия', 'digital'],
  },
  {
    background: 'bg-bg-7-1',
    title: 'Rebranding RML',
    link: '/case2',
    cards: ['брендинг', '3d'],
  },
  {
    background: 'bg-bg-8-1',
    title: 'запуск Косметологии',
    link: '/case5',
    cards: ['events', 'архитектура'],
  },
  {
    background: 'bg-bg-9-1',
    title: '«Исполнение мечты»',
    link: '/case11',
    cards: ['Digital', 'UX/UI-дизайн'],
  },
  {
    background: 'bg-bg-10-1',
    title: 'форма ФК « Спартак »',
    link: '/case13',
    cards: ['мерч', '3d'],
  },
  {
    background: 'bg-bg-11-1',
    title: '«Капитальный прыжок»',
    link: '/case14',
    cards: ['Digital', 'UX/UI-дизайн', '3d'],
  },
  {
    background: 'bg-bg-12-1',
    title: 'Limitless opportunities',
    link: '/case8',
    cards: ['мерч'],
  },
  {
    background: 'bg-bg-13-1',
    title: 'GRAND OPENING',
    link: '/case6',
    cards: ['events'],
  },
  {
    background: 'bg-bg-14-1',
    title: 'SBER BAZAR',
    link: '/case4',
    cards: ['events', 'брендинг'],
  },
  {
    background: 'bg-bg-15-1',
    title: 'create your reality?',
    link: '/case12',
    cards: [],
  },
  {
    background: 'bg-bg-16-1',
    backgroundNext: 'bg-next-16',
    title: 'Хвоя by Pine River',
    link: '/case16',
    cards: ['брендинг'],
  },
  {
    background: 'bg-bg-17-1',
    backgroundNext: 'bg-next-17',
    title: '«Тим Фест»',
    link: '/case17',
    cards: ['брендинг', 'партнерство', 'стратегия', 'позиционирование'],
  },
  {
    background: 'bg-bg-16',
    backgroundNext: 'bg-next-18',
    title: 'САМОЛет SELECT х Lunda Padel',
    link: '/case18',
    cards: ['брендинг', '3d', 'партнерство', 'events'],
  },
  {
    background: 'bg-bg-19',
    backgroundNext: 'bg-next-19',
    title: 'Фонда мельниченко "движфест "',
    link: '/case19',
    cards: ['events'],
  },
  {
    background: 'bg-bg-20',
    backgroundNext: 'bg-next-20',
    title: 'гольф-клуб «Пестово»',
    link: '/case20',
    cards: ['стратегия', 'брендинг', 'партнерство', 'events'],
  },
  {
    background: 'bg-bg-21',
    backgroundNext: 'bg-next-21',
    title: 'МЕРЧ  lunda  Padel',
    link: '/case21',
    cards: ['мерч'],
  },
  {
    background: 'bg-bg-22',
    backgroundNext: 'bg-next-22',
    title: 'BetBoom Медиа бильярд',
    link: '/case22',
    cards: ['events', 'Digital'],
  },
];