export const casesData = [
  {
    background: 'bg-bg-1',
    title: 'Лига уличного футбола',
    link: '/case15',
    cards: ['брендинг', 'UX/UI-дизайн', 'events', 'партнерство', 'SMM/PR', 'production'],
  },
  {
    background: 'bg-bg-2-1',
    title: 'запуск nrav',
    link: '/case3',
    cards: ['events'],
  },
  {
    background: 'bg-bg-3',
    title: 'Pop-up «Самолет»',
    link: '/case7',
    cards: ['events', 'архитектура'],
  },
  {
    background: 'bg-bg-4',
    title: 'Rebranding lunda',
    link: '/case10',
    cards: ['брендинг', '3d', 'партнерство'],
  },
  {
    background: 'bg-bg-5-1',
    title: 'betboom party',
    link: '/case9',
    cards: ['events'],
  },
  {
    background: 'bg-bg-6-1',
    title: 'маскот УК « Альфа-капитал »',
    link: '/case1',
    cards: ['3d', 'стратегия', 'digital'],
  },
  {
    background: 'bg-bg-7-1',
    title: 'Rebranding RML',
    link: '/case2',
    cards: ['брендинг', '3d'],
  },
  {
    background: 'bg-bg-8-1',
    title: 'запуск Косметологии',
    link: '/case5',
    cards: ['events', 'архитектура'],
  },
  {
    background: 'bg-bg-9-1',
    title: '«Исполнение мечты»',
    link: '/case11',
    cards: ['Digital', 'UX/UI-дизайн'],
  },
  {
    background: 'bg-bg-10-1',
    title: 'форма ФК « Спартак »',
    link: '/case13',
    cards: ['мерч', '3d'],
  },
  {
    background: 'bg-bg-11-1',
    title: '«Капитальный прыжок»',
    link: '/case14',
    cards: ['Digital', 'UX/UI-дизайн', '3d'],
  },
  {
    background: 'bg-bg-12-1',
    title: 'Limitless opportunities',
    link: '/case8',
    cards: ['мерч'],
  },
  {
    background: 'bg-bg-13-1',
    title: 'GRAND OPENING',
    link: '/case6',
    cards: ['events'],
  },
  {
    background: 'bg-bg-14-1',
    title: 'SBER BAZAR',
    link: '/case4',
    cards: ['events', 'брендинг', 'SMM/PR'],
  },
  {
    background: 'bg-bg-15-1',
    title: 'create your reality?',
    link: '/case12',
    cards: ['SMM/PR', 'production'],
  },
];